#작가유저 회원가입  정상 요청
POST {{host}}/api/v1/users/artist
Content-Type: application/json

{
  "name": "준식",
  "nickname": "온프리!!",
  "email": "joon1@naver.com",
  "password": "!Abcderghijk112",
  "newsAgency": "SKT",
  "phoneNumber": "010-8888-9999",
  "bankName": "IBK_BANK",
  "accountNumber": "010-8888-9999",
  "serviceAgree": true,
  "policyAgree": true,
  "personalInfoAgree": true,
  "advertisementAgree": true,
  "adultCertification": true,
  "gender": "MAN",
  "profileImage": "http://onfree.io/images/123456789",
  "portfolioUrl": "joon"
}

### 작가유저 회원가입 데이터 누락
POST {{host}}/api/v1/users/artist
Content-Type: application/json

{
  "name": "",
  "email": "jun@naver.com",
  "newsAgency": "SKT",
  "phoneNumber": "",
  "bankName": "IBK_BANK",
  "accountNumber": "010-8888-9999",
  "serviceAgree": true,
  "policyAgree": true,
  "personalInfoAgree": true,
  "advertisementAgree": true,
  "adultCertification": true,
  "gender": "MAN",
  "profileImage": "http://onfree.io/images/123456789",
  "portfolioUrl": "http://onfree.io/images/123456789"

}

### 회원 정보 조회
GET {{host}}/api/v1/users/artist/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb29uQG5hdmVyLmNvbSIsInVpZCI6MSwiaXNzIjoib25mcmVlLmNvbSIsImV4cCI6MTYzOTkyMzM5OH0.D7yAeff3TXO11a58yWZXeXllrzkG-YRPP5jUe0nTWTPxjCf4G-QeZQBiNXatilJmG8Cldb1BNYIINc7ETBVKOw

### 회원 제거
DELETE {{host}}/api/v1/users/artist/1
Content-Type: application/json

### 회원정보 수정
PUT {{host}}/api/v1/users/artist/1
Content-Type: application/json

{
  "nickname": "온프리프리123",
  "newsAgency": "SKT1123",
  "phoneNumber": "010-0000-0000",
  "bankName": "IBK_BANK",
  "accountNumber": "010-0000-0000",
  "adultCertification": true,
  "profileImage": "http://onfree.io/images/1",
  "portfolioUrl": "http://onfree.io/images/1"
}

