name: docker_CI

on:
  push:
    branches: [ develop, feature/*]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: .gradlew build
      - name: Docker build
        run: |
          docker login - u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
          docker build -t wnstlr0615/spring-onfree .
      - name: Docker push
        run: docker push wnstlr0615/spring-onfree
        
